package com.example.focuslock;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.util.*;
public class ScheduleActivity extends Activity {
 private LinearLayout content;private EditText name;private final CheckBox[] days=new CheckBox[7];private Switch strict,enabled;private int start=19*60,end=22*60,ink,muted,bg,card,accent;private String id="";private Set<String> picked=new HashSet<>();private boolean protectedNow;
 private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density);}
 private TextView text(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(ink);v.setPadding(0,dp(12),0,dp(8));return v;}
 private Button button(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(ink);b.setOnClickListener(v->r.run());return b;}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 @Override public void onCreate(Bundle b){super.onCreate(b);boolean dark=FocusState.p(this).getBoolean("dark",true);bg=Color.parseColor(dark?"#0D1423":"#F4F7FA");card=Color.parseColor(dark?"#182235":"#FFFFFF");ink=Color.parseColor(dark?"#F1F5FC":"#182235");muted=Color.parseColor(dark?"#9CAFC7":"#53657E");accent=Color.parseColor("#75E5C2");id=b!=null?b.getString("id"):getIntent().getStringExtra("id");if(id==null)id=UUID.randomUUID().toString();WeeklySchedule loaded=null;for(WeeklySchedule s:FocusState.schedules(this))if(s.id.equals(id))loaded=s;
  if(b!=null)picked.addAll(b.getStringArrayList("apps")==null?new ArrayList<>():b.getStringArrayList("apps"));
  if(loaded!=null){start=loaded.startMinute;end=loaded.endMinute;if(b==null)picked.addAll(loaded.apps);protectedNow=loaded.strict&&loaded.active(System.currentTimeMillis());}
  getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setBackgroundColor(bg);setContentView(shell);shell.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});shell.post(()->{if(Build.VERSION.SDK_INT>=30&&getWindow().getInsetsController()!=null){int mask=WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS;getWindow().getInsetsController().setSystemBarsAppearance(dark?0:mask,mask);}});
  ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(24),dp(16),dp(24),dp(24));scroll.addView(content);shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));content.addView(text("매주 반복하는 잠금",26));content.addView(text("선택한 요일의 시작 시각부터 잠급니다.",14));if(protectedNow)content.addView(text("실행 중인 엄격 예약은 수정·삭제할 수 없어요.",15));
  name=new EditText(this);name.setSingleLine(true);name.setTextColor(ink);name.setHintTextColor(muted);name.setHint("예약 이름 · 예: 평일 저녁");if(loaded!=null)name.setText(loaded.name);name.setEnabled(!protectedNow);content.addView(name);
  content.addView(text("요일",18));LinearLayout row=new LinearLayout(this);String[] names={"월","화","수","목","금","토","일"};for(int n=0;n<7;n++){if(n==4){content.addView(row);row=new LinearLayout(this);}days[n]=new CheckBox(this);days[n].setText(names[n]);days[n].setTextColor(ink);days[n].setTextSize(12);days[n].setPadding(0,0,0,0);days[n].setButtonTintList(android.content.res.ColorStateList.valueOf(accent));days[n].setChecked(loaded==null?n<5:(loaded.days&(1<<n))!=0);days[n].setEnabled(!protectedNow);row.addView(days[n],new LinearLayout.LayoutParams(0,-2,1));}content.addView(row);
  Button from=button("",()->{}),to=button("",()->{});from.setText("시작  "+clock(start));to.setText("종료  "+clock(end));from.setEnabled(!protectedNow);to.setEnabled(!protectedNow);from.setOnClickListener(v->new TimePickerDialog(this,(t,h,m)->{start=h*60+m;from.setText("시작  "+clock(start));},start/60,start%60,true).show());to.setOnClickListener(v->new TimePickerDialog(this,(t,h,m)->{end=h*60+m;to.setText("종료  "+clock(end));},end/60,end%60,true).show());content.addView(from);content.addView(to);content.addView(text("종료가 시작보다 이르면 다음 날 종료돼요.\n시간대는 휴대폰의 현재 현지 시간을 따릅니다.",13));
  strict=new Switch(this);strict.setText("엄격 예약");strict.setTextColor(ink);strict.setChecked(loaded!=null&&loaded.strict);strict.setEnabled(!protectedNow);content.addView(strict);content.addView(text("실행 중에만 이 예약의 수정·삭제·끄기를 막아요.",13));enabled=new Switch(this);enabled.setText("예약 사용");enabled.setTextColor(ink);enabled.setChecked(loaded==null||loaded.enabled);enabled.setEnabled(!protectedNow);content.addView(enabled);
  content.addView(text("이 예약에서 잠글 앱",18));EditText search=new EditText(this);search.setSingleLine(true);search.setTextColor(ink);search.setHintTextColor(muted);search.setHint("앱 이름 검색");content.addView(search);PackageManager pm=getPackageManager();List<ResolveInfo> entries=pm.queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0);entries.sort(Comparator.comparing(x->x.loadLabel(pm).toString(),String.CASE_INSENSITIVE_ORDER));Set<String> seen=new HashSet<>();List<View> rows=new ArrayList<>();ResolveInfo home=pm.resolveActivity(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME),0);String homePkg=home==null?"":home.activityInfo.packageName;android.telecom.TelecomManager tm=(android.telecom.TelecomManager)getSystemService(TELECOM_SERVICE);String dialer=tm==null?"":tm.getDefaultDialerPackage();
  for(ResolveInfo info:entries){String pkg=info.activityInfo.packageName;if(!seen.add(pkg)||pkg.equals(getPackageName())||pkg.equals("com.android.settings")||pkg.equals(homePkg)||pkg.equals(dialer))continue;LinearLayout item=new LinearLayout(this);item.setGravity(Gravity.CENTER_VERTICAL);item.setPadding(dp(8),dp(4),dp(8),dp(4));ImageView icon=new ImageView(this);icon.setImageDrawable(info.loadIcon(pm));item.addView(icon,new LinearLayout.LayoutParams(dp(32),dp(32)));CheckBox cb=new CheckBox(this);cb.setText(info.loadLabel(pm));cb.setTextColor(ink);cb.setChecked(picked.contains(pkg));cb.setEnabled(!protectedNow);cb.setButtonTintList(android.content.res.ColorStateList.valueOf(accent));cb.setOnCheckedChangeListener((v,on)->{if(on)picked.add(pkg);else picked.remove(pkg);});item.addView(cb,new LinearLayout.LayoutParams(-1,-2));item.setTag(info.loadLabel(pm).toString().toLowerCase(Locale.getDefault()));content.addView(item);rows.add(item);}
  search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){String q=s.toString().toLowerCase(Locale.getDefault());for(View v:rows)v.setVisibility(v.getTag().toString().contains(q)?View.VISIBLE:View.GONE);}public void afterTextChanged(Editable e){}});
  LinearLayout actions=new LinearLayout(this);actions.setPadding(dp(16),dp(8),dp(16),dp(8));actions.addView(button("취소",this::finish),new LinearLayout.LayoutParams(0,dp(56),1));Button save=button("예약 저장",this::save);save.setEnabled(!protectedNow);actions.addView(save,new LinearLayout.LayoutParams(0,dp(56),1));shell.addView(actions);
  if(b!=null){name.setText(b.getString("name",""));start=b.getInt("start",start);end=b.getInt("end",end);from.setText("시작  "+clock(start));to.setText("종료  "+clock(end));int mask=b.getInt("days",0);for(int n=0;n<7;n++)days[n].setChecked((mask&(1<<n))!=0);strict.setChecked(b.getBoolean("strict"));enabled.setChecked(b.getBoolean("enabled",true));}
 }
 @Override protected void onSaveInstanceState(Bundle b){b.putString("name",name.getText().toString());b.putInt("start",start);b.putInt("end",end);int mask=0;for(int i=0;i<7;i++)if(days[i].isChecked())mask|=1<<i;b.putInt("days",mask);b.putBoolean("strict",strict.isChecked());b.putBoolean("enabled",enabled.isChecked());b.putStringArrayList("apps",new ArrayList<>(picked));b.putString("id",id);super.onSaveInstanceState(b);}
 private void save(){int mask=0;for(int i=0;i<7;i++)if(days[i].isChecked())mask|=1<<i;if(mask==0||picked.isEmpty()||start==end){toast("요일·차단 앱을 선택하고 서로 다른 시작·종료 시각을 지정하세요.");return;}String title=name.getText().toString().trim();if(title.isEmpty())title="나의 예약";WeeklySchedule s=new WeeklySchedule(id,title,mask,start,end,strict.isChecked(),enabled.isChecked(),picked);if(!FocusState.save(this,s)){toast("실행 중인 엄격 예약은 변경할 수 없어요.");return;}toast("예약을 저장했어요");finish();}
 static String clock(int n){return String.format(Locale.ROOT,"%02d:%02d",n/60,n%60);}
}
