package com.example.focuslock;
import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;
public class FlowTests extends Instrumentation {
 private int passed=0; private String mode="";
 private void check(boolean v,String name){if(!v)throw new AssertionError(name);passed++;if(mode.equals("live")){Bundle b=new Bundle();b.putString("stream","LIVE "+passed+": "+name+"\n");sendStatus(0,b);}}
 @Override public void onCreate(Bundle b){super.onCreate(b);mode=b==null?"":b.getString("mode","");start();}
 @Override public void onStart(){Bundle result=new Bundle();try{
  Context c=getTargetContext();c.getSharedPreferences(LockPrefs.PREFS,0).edit().clear().commit();
  if(mode.equals("live")){live(c,result);return;}
  if(mode.equals("block")){LockPrefs.start(c,new HashSet<>(Arrays.asList("com.example.focusfixture")),30000,true);result.putString("stream","BLOCK_SETUP\n");finish(Activity.RESULT_OK,result);return;}
  check(!LockPrefs.active(c),"initial unlocked");
  LockPrefs.start(c,new HashSet<>(),60000,true);check(!LockPrefs.active(c),"empty selection rejected");
  Set<String> apps=new HashSet<>();apps.add("com.android.chrome");
  LockPrefs.start(c,apps,60000,false);check(LockPrefs.active(c)&&!LockPrefs.strict(c),"normal start");
  LockPrefs.stop(c);check(!LockPrefs.active(c),"normal early stop");
  LockPrefs.start(c,apps,60000,true);check(LockPrefs.strict(c),"strict start");
  long before=LockPrefs.remaining(c);LockPrefs.stop(c);check(LockPrefs.active(c),"strict early stop rejected");
  LockPrefs.start(c,new HashSet<>(Arrays.asList("other")),1000,false);check(LockPrefs.selected(c).equals(apps)&&LockPrefs.strict(c),"active reconfiguration rejected");
  c.getSharedPreferences(LockPrefs.PREFS,0).edit().putLong(LockPrefs.KEY_END,1).commit();check(LockPrefs.remaining(c)>before-10000,"wall clock does not shorten current boot");
  c.getSharedPreferences(LockPrefs.PREFS,0).edit().putLong("elapsed_end",SystemClock.elapsedRealtime()-1).commit();check(!LockPrefs.active(c)&&!LockPrefs.strict(c),"automatic expiry");
  LockPrefs.stop(c);
  Calendar now=Calendar.getInstance();int minute=now.get(Calendar.HOUR_OF_DAY)*60+now.get(Calendar.MINUTE);Set<String> fixture=new HashSet<>(Arrays.asList("com.example.focusfixture"));
  WeeklySchedule strictSchedule=new WeeklySchedule("strict","매일 엄격",127,(minute+1439)%1440,(minute+2)%1440,true,true,fixture);
  check(FocusState.save(c,strictSchedule),"save new strict schedule");
  check(FocusState.schedules(c).size()==1&&FocusState.schedules(c).get(0).active(System.currentTimeMillis()),"persisted active weekly schedule");
  check(!FocusState.delete(c,"strict"),"running strict deletion rejected");
  check(!FocusState.save(c,new WeeklySchedule("strict","changed",127,minute,(minute+2)%1440,false,false,fixture)),"running strict edit rejected");
  WeeklySchedule normal=new WeeklySchedule("normal","일반 예약",127,(minute+1439)%1440,(minute+2)%1440,false,true,fixture);check(FocusState.save(c,normal)&&FocusState.schedules(c).size()==2,"multiple independent schedules");check(FocusState.delete(c,"normal"),"normal schedule deletable while active");
  c.getSharedPreferences(LockPrefs.PREFS,0).edit().putString("schedules","[]").commit();
  FocusState.creditAutomatic(c,3600000);check(FocusState.coins(c)==1,"automatic hourly reward");
  check(FocusState.start(c,3600000),"focus start");FocusState.cancel(c,"cancelled");check(FocusState.coins(c)==1&&!FocusState.focusActive(c),"abandon gives no reward");
  FocusState.start(c,3600000);c.getSharedPreferences(LockPrefs.PREFS,0).edit().putLong("focus_end",SystemClock.elapsedRealtime()-1).commit();FocusState.settle(c);check(FocusState.coins(c)==11,"focus completion adds ten alongside automatic");FocusState.settle(c);check(FocusState.coins(c)==11,"completion idempotent");
  FocusState.start(c,3600000);c.getSharedPreferences(LockPrefs.PREFS,0).edit().putInt("focus_boot",-99).commit();FocusState.settle(c);check(FocusState.coins(c)==11&&!FocusState.focusActive(c),"reboot cancels focus reward");
  c.getSharedPreferences(LockPrefs.PREFS,0).edit().clear().commit();
  Intent i=new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);Activity a=startActivitySync(i);waitForIdleSync();
  runOnMainSync(()->{View root=a.findViewById(android.R.id.content);check(find(root,"앱 잠금 시작")!=null,"start flow visible");check(find(root,"엄격 모드")!=null,"strict choice visible");find(root,"예약").performClick();check(find(root,"＋ 예약 추가")!=null,"schedule UI visible");find(root,"집중").performClick();check(find(root,"집중모드 시작")!=null&&find(root,"잔잔한 BGM")!=null,"focus and music controls visible");find(root,"상점").performClick();check(find(root,"상점 준비 중")!=null,"shop UI visible");find(root,"잠금").performClick();});
  result.putString("stream","PASS "+passed+" checks\n");finish(Activity.RESULT_OK,result);
 }catch(Throwable t){if(mode.equals("live")&&automation!=null){try{dump("live-accessibility","dumpsys accessibility");dump("live-activity","dumpsys activity services com.example.focuslock");dump("live-logcat","logcat -d");}catch(Exception ignored){}}result.putString("stream","FAIL: "+t);finish(Activity.RESULT_CANCELED,result);}}
 private android.app.UiAutomation automation;
 private void shell(String command)throws Exception{android.os.ParcelFileDescriptor fd=automation.executeShellCommand(command);try(java.io.InputStream in=new android.os.ParcelFileDescriptor.AutoCloseInputStream(fd)){while(in.read()!=-1){}}}
 private void dump(String name,String command)throws Exception{android.os.ParcelFileDescriptor fd=automation.executeShellCommand(command);try(java.io.InputStream in=new android.os.ParcelFileDescriptor.AutoCloseInputStream(fd);java.io.OutputStream out=new java.io.FileOutputStream(new java.io.File(getTargetContext().getFilesDir(),name+".txt"))){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);}}
 private void screenshot(String name)throws Exception{waitForIdleSync();SystemClock.sleep(500);android.graphics.Bitmap bitmap=automation.takeScreenshot();if(bitmap==null)throw new AssertionError("screenshot "+name);try(java.io.OutputStream out=new java.io.FileOutputStream(new java.io.File(getTargetContext().getFilesDir(),name+".png"))){bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();}
 private void uiClick(String label)throws Exception{for(int n=0;n<50;n++){List<android.view.accessibility.AccessibilityNodeInfo> roots=new ArrayList<>();android.view.accessibility.AccessibilityNodeInfo active=automation.getRootInActiveWindow();if(active!=null)roots.add(active);for(android.view.accessibility.AccessibilityWindowInfo window:automation.getWindows()){android.view.accessibility.AccessibilityNodeInfo root=window.getRoot();if(root!=null)roots.add(root);}for(android.view.accessibility.AccessibilityNodeInfo root:roots)for(android.view.accessibility.AccessibilityNodeInfo node:root.findAccessibilityNodeInfosByText(label)){if(label.equals(String.valueOf(node.getText()))&&node.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK)){SystemClock.sleep(300);return;}}SystemClock.sleep(100);}throw new AssertionError("UI missing: "+label);}
 private boolean has(Activity a,String label){final boolean[] found={false};runOnMainSync(()->found[0]=find(a.findViewById(android.R.id.content),label)!=null);return found[0];}
 private void waitFor(java.util.function.BooleanSupplier condition,String name)throws Exception{for(int n=0;n<200;n++){if(condition.getAsBoolean()){check(true,name);return;}SystemClock.sleep(100);}throw new AssertionError(name);}
 private void live(Context c,Bundle result)throws Exception{
  automation=getUiAutomation(android.app.UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES);android.accessibilityservice.AccessibilityServiceInfo info=automation.getServiceInfo();info.flags|=android.accessibilityservice.AccessibilityServiceInfo.FLAG_RETRIEVE_INTERACTIVE_WINDOWS;automation.setServiceInfo(info);
  shell("settings put secure enabled_accessibility_services null");shell("settings put secure accessibility_enabled 0");SystemClock.sleep(500);Activity warm=startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));waitForIdleSync();shell("settings put secure enabled_accessibility_services com.example.focuslock/com.example.focuslock.AppWatchService");shell("settings put secure accessibility_enabled 1");waitFor(()->AppWatchService.connected,"service connected during live tests");
  FocusState.p(c).edit().putLong("focus_draft",60000).putBoolean("bgm",true).commit();final Activity a=warm;waitForIdleSync();runOnMainSync(()->find(a.findViewById(android.R.id.content),"집중").performClick());screenshot("focus-ready");runOnMainSync(()->find(a.findViewById(android.R.id.content),"집중모드 시작").performClick());uiClick("집중 시작");check(FocusState.focusActive(c),"real focus confirmation starts session");waitFor(()->CalmMusicService.playing,"BGM plays through foreground service");screenshot("focus-running");
  runOnMainSync(()->find(a.findViewById(android.R.id.content),"느린 구름").performClick());waitFor(()->CalmMusicService.selectedTrack==1&&CalmMusicService.playing,"second BGM plays");runOnMainSync(()->find(a.findViewById(android.R.id.content),"비 오는 창가").performClick());waitFor(()->CalmMusicService.selectedTrack==2&&CalmMusicService.playing,"live BGM track switch");runOnMainSync(()->find(a.findViewById(android.R.id.content),"잔잔한 BGM").performClick());waitFor(()->!CalmMusicService.playing,"BGM off stops audio");runOnMainSync(()->find(a.findViewById(android.R.id.content),"잔잔한 BGM").performClick());waitFor(()->CalmMusicService.playing,"BGM on resumes audio");
  shell("am start -n com.example.focusfixture/.FixtureActivity");SystemClock.sleep(1200);screenshot("focus-blocked");uiClick("이번 집중 포기하기");screenshot("quit-confirmation");uiClick("아니오, 계속할게요");check(FocusState.focusActive(c),"declining quit keeps session");uiClick("이번 집중 포기하기");uiClick("예, 종료할게요");check(!FocusState.focusActive(c)&&FocusState.coins(c)==0,"overlay quit gives zero coins");waitFor(()->!CalmMusicService.playing,"quitting stops audio");
  FocusState.p(c).edit().putBoolean("bgm",false).commit();shell("am start -n com.example.focuslock/.MainActivity");final Activity completion=warm;waitForIdleSync();waitFor(()->has(completion,"집중모드 시작"),"focus-ready view resumed");runOnMainSync(()->{View root=completion.findViewById(android.R.id.content);if(find(root,"집중")!=null)find(root,"집중").performClick();find(completion.findViewById(android.R.id.content),"집중모드 시작").performClick();});uiClick("집중 시작");shell("am start -n com.example.focusfixture/.FixtureActivity");for(int n=0;n<70&&FocusState.focusActive(c);n++)SystemClock.sleep(1000);SystemClock.sleep(1200);check(!FocusState.focusActive(c)&&FocusState.p(c).getLong("focus_completed_ms",0)==60000,"real timed focus completes and accrues only completed duration");check(FocusState.p(c).getString("focus_result","").startsWith("집중 완료"),"real completion result");screenshot("focus-expired");
  Calendar now=Calendar.getInstance();int minute=now.get(Calendar.HOUR_OF_DAY)*60+now.get(Calendar.MINUTE);WeeklySchedule schedule=new WeeklySchedule("live","자동 잠금 실기동",127,(minute+1439)%1440,(minute+2)%1440,true,true,new HashSet<>(Arrays.asList("com.example.focusfixture")));runOnMainSync(()->FocusState.save(c,schedule));SystemClock.sleep(1500);screenshot("scheduled-blocked");uiClick("홈으로 돌아가서 집중하기");check(FocusState.p(c).getLong("auto_ms",0)>0,"connected schedule time accrues");check(!FocusState.delete(c,"live"),"active strict deletion rejected live");
  runOnMainSync(()->FocusState.p(c).edit().putString("schedules","[]").commit());shell("am start -n com.example.focuslock/.MainActivity");final Activity main=warm;waitForIdleSync();waitFor(()->has(main,"예약"),"main navigation resumed");SystemClock.sleep(500);runOnMainSync(()->find(main.findViewById(android.R.id.content),"예약").performClick());screenshot("schedules");android.app.Instrumentation.ActivityMonitor monitor=addMonitor(ScheduleActivity.class.getName(),null,false);runOnMainSync(()->find(main.findViewById(android.R.id.content),"＋ 예약 추가").performClick());Activity editor=waitForMonitorWithTimeout(monitor,5000);check(editor!=null,"editor opens");waitForIdleSync();screenshot("schedule-editor");runOnMainSync(()->{View root=editor.findViewById(android.R.id.content);View cb=find(root,"FocusLock Test App");check(cb!=null,"installed app choice visible");cb.performClick();find(root,"예약 저장").performClick();});waitForIdleSync();check(FocusState.schedules(c).size()==1&&FocusState.schedules(c).get(0).apps.contains("com.example.focusfixture"),"editor saves selected target");screenshot("schedule-saved");runOnMainSync(()->find(main.findViewById(android.R.id.content),"상점").performClick());screenshot("shop");
  result.putString("stream","PASS LIVE "+passed+" checks: focus overlay, zero-reward quit, three BGM controls, scheduled overlay and editor\n");finish(Activity.RESULT_OK,result);
 }
 private View find(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().equals(text))return v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int n=0;n<g.getChildCount();n++){View f=find(g.getChildAt(n),text);if(f!=null)return f;}}return null;}
}
